# Generated by Django 2.2.2 on 2019-10-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('post_text', models.CharField(max_length=100)),
                ('post_img', models.CharField(max_length=50)),
            ],
        ),
    ]
